create table if not exists public.ai_knowledge_chunks (
    id bigint generated by default as identity primary key,
    organization_id uuid not null,
    entity_type text not null default '',
    entity_id text not null default '',
    source_scope text not null default '',
    title text not null default '',
    content text not null default '',
    search_text text not null default '',
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_ai_knowledge_chunks_org on public.ai_knowledge_chunks (organization_id);
create index if not exists idx_ai_knowledge_chunks_entity on public.ai_knowledge_chunks (organization_id, entity_type, entity_id);
create index if not exists idx_ai_knowledge_chunks_scope on public.ai_knowledge_chunks (organization_id, source_scope);

alter table public.ai_knowledge_chunks enable row level security;

drop trigger if exists set_ai_knowledge_chunks_updated_at on public.ai_knowledge_chunks;
create trigger set_ai_knowledge_chunks_updated_at
before update on public.ai_knowledge_chunks
for each row
execute function public.set_updated_at();
