create table if not exists public.clients (
    id bigint generated by default as identity primary key,
    type text not null check (type in ('PF', 'PJ')),
    nome text not null default '',
    cpf text not null default '',
    nome_fantasia text not null default '',
    cnpj text not null default '',
    nome_empresarial text not null default '',
    email text not null default '',
    telefone text not null default '',
    logradouro text not null default '',
    numero text not null default '',
    bairro text not null default '',
    cidade text not null default '',
    uf text not null default '',
    cep text not null default '',
    documents jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.processes (
    id bigint generated by default as identity primary key,
    client_id bigint not null references public.clients(id) on delete restrict,
    project_name text not null default '',
    fase text not null default 'Requerimento',
    tipo text not null default '',
    tipo_sigla text not null default '',
    tipologia text not null default '',
    area text not null default '',
    municipio text not null default '',
    orgao_sigla text not null default '',
    orgao_nome_completo text not null default '',
    orgao text not null default '',
    numero_processo text not null default '',
    data_protocolo date,
    numero_titulo text not null default '',
    data_validade date,
    data_outorga date,
    deadlines jsonb not null default '[]'::jsonb,
    events jsonb not null default '[]'::jsonb,
    doc_base64 text not null default '',
    doc_storage_path text not null default '',
    doc_name text not null default '',
    doc_type text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_processes_client_id on public.processes (client_id);
create index if not exists idx_processes_project_name on public.processes (project_name);
create index if not exists idx_clients_type on public.clients (type);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_clients_updated_at on public.clients;
create trigger set_clients_updated_at
before update on public.clients
for each row
execute function public.set_updated_at();

drop trigger if exists set_processes_updated_at on public.processes;
create trigger set_processes_updated_at
before update on public.processes
for each row
execute function public.set_updated_at();
