create table if not exists public.user_preferences (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    organization_id uuid references public.organizations(id) on delete cascade,
    preference_key text not null,
    preference_value jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create unique index if not exists idx_user_preferences_global_unique
on public.user_preferences (user_id, preference_key)
where organization_id is null;

create unique index if not exists idx_user_preferences_org_unique
on public.user_preferences (user_id, organization_id, preference_key)
where organization_id is not null;

create index if not exists idx_user_preferences_user_id
on public.user_preferences (user_id);

create index if not exists idx_user_preferences_org_id
on public.user_preferences (organization_id);

drop trigger if exists set_user_preferences_updated_at on public.user_preferences;
create trigger set_user_preferences_updated_at
before update on public.user_preferences
for each row
execute function public.set_updated_at();

alter table public.user_preferences enable row level security;

drop policy if exists "read own preferences" on public.user_preferences;
create policy "read own preferences"
on public.user_preferences
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "insert own preferences" on public.user_preferences;
create policy "insert own preferences"
on public.user_preferences
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "update own preferences" on public.user_preferences;
create policy "update own preferences"
on public.user_preferences
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "delete own preferences" on public.user_preferences;
create policy "delete own preferences"
on public.user_preferences
for delete
to authenticated
using (auth.uid() = user_id);
