create table if not exists public.ai_provider_configs (
    id bigint generated by default as identity primary key,
    organization_id uuid not null,
    label text not null default '',
    provider text not null default '',
    api_key text not null default '',
    base_url text not null default '',
    is_enabled boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (organization_id, provider, label)
);

create table if not exists public.ai_models (
    id bigint generated by default as identity primary key,
    organization_id uuid not null,
    name text not null default '',
    slug text not null default '',
    provider text not null default '',
    model text not null default '',
    api_config_id bigint references public.ai_provider_configs(id) on delete set null,
    temperature_default numeric not null default 0.2,
    max_tokens_default integer not null default 4096,
    is_active boolean not null default true,
    supports_chat boolean not null default true,
    supports_rag boolean not null default false,
    supports_tools boolean not null default false,
    cost_input_per_million numeric not null default 0,
    cost_output_per_million numeric not null default 0,
    currency text not null default 'BRL',
    notes text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (organization_id, slug)
);

create table if not exists public.ai_agents (
    id bigint generated by default as identity primary key,
    organization_id uuid not null,
    slug text not null default '',
    name text not null default '',
    description text not null default '',
    is_enabled boolean not null default false,
    ai_model_id bigint references public.ai_models(id) on delete set null,
    system_prompt text not null default '',
    allowed_tools jsonb not null default '[]'::jsonb,
    allowed_modules jsonb not null default '[]'::jsonb,
    monthly_token_limit bigint not null default 0,
    monthly_cost_limit_brl numeric(12,2) not null default 0,
    priority integer not null default 0,
    visibility_scope text not null default 'admin',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (organization_id, slug)
);

create table if not exists public.ai_usage_logs (
    id bigint generated by default as identity primary key,
    organization_id uuid not null,
    user_id uuid,
    agent_slug text not null default '',
    ai_model_id bigint references public.ai_models(id) on delete set null,
    provider text not null default '',
    model text not null default '',
    model_label text not null default '',
    feature text not null default '',
    input_tokens integer not null default 0,
    output_tokens integer not null default 0,
    total_tokens integer not null default 0,
    estimated_cost numeric(12,6) not null default 0,
    currency text not null default 'BRL',
    request_status text not null default 'success',
    request_meta jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now()
);

create index if not exists idx_ai_provider_configs_org on public.ai_provider_configs (organization_id);
create index if not exists idx_ai_models_org on public.ai_models (organization_id);
create index if not exists idx_ai_agents_org on public.ai_agents (organization_id);
create index if not exists idx_ai_usage_logs_org_created on public.ai_usage_logs (organization_id, created_at desc);

alter table public.ai_provider_configs enable row level security;
alter table public.ai_models enable row level security;
alter table public.ai_agents enable row level security;
alter table public.ai_usage_logs enable row level security;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists set_ai_provider_configs_updated_at on public.ai_provider_configs;
create trigger set_ai_provider_configs_updated_at
before update on public.ai_provider_configs
for each row
execute function public.set_updated_at();

drop trigger if exists set_ai_models_updated_at on public.ai_models;
create trigger set_ai_models_updated_at
before update on public.ai_models
for each row
execute function public.set_updated_at();

drop trigger if exists set_ai_agents_updated_at on public.ai_agents;
create trigger set_ai_agents_updated_at
before update on public.ai_agents
for each row
execute function public.set_updated_at();
